apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx